USE [master]
GO

/****** Object:  Database [NoteBd]    Script Date: 23.05.2023 11:21:31 ******/
CREATE DATABASE [NoteBd]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'NoteBd', FILENAME = N'F:\MSSQL14.MSSQLSERVER1\MSSQL\DATA\NoteBd.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'NoteBd_log', FILENAME = N'F:\MSSQL14.MSSQLSERVER1\MSSQL\DATA\NoteBd_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [NoteBd].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [NoteBd] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [NoteBd] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [NoteBd] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [NoteBd] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [NoteBd] SET ARITHABORT OFF 
GO

ALTER DATABASE [NoteBd] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [NoteBd] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [NoteBd] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [NoteBd] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [NoteBd] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [NoteBd] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [NoteBd] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [NoteBd] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [NoteBd] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [NoteBd] SET  DISABLE_BROKER 
GO

ALTER DATABASE [NoteBd] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [NoteBd] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [NoteBd] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [NoteBd] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [NoteBd] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [NoteBd] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [NoteBd] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [NoteBd] SET RECOVERY FULL 
GO

ALTER DATABASE [NoteBd] SET  MULTI_USER 
GO

ALTER DATABASE [NoteBd] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [NoteBd] SET DB_CHAINING OFF 
GO

ALTER DATABASE [NoteBd] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [NoteBd] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [NoteBd] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [NoteBd] SET QUERY_STORE = OFF
GO

ALTER DATABASE [NoteBd] SET  READ_WRITE 
GO

